name: Docusaurus Build
run-name: Docusaurus Build
on: [push]
jobs:
  Docusaurus-Build:
    runs-on: docusaurus
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
        
      - run: pwd
      - run: whoami
      - run: ls -la


